blank_issues_enabled: true
contact_links:
  - name: ğŸ¦ Jonas BrÃ¶ms Twitter
    url: https://twitter.com/jonasbroms
    about: The official Twitter account to ask questions and get help with any open-source projects by me
  - name: ğŸ“˜ Jonas BrÃ¶ms Facebook
    url: https://www.facebook.com/jonasbroms
    about: Ask questions, get help and discuss new things you're building with me
  - name: ğŸ“· Jonas BrÃ¶ms Instagram
    url: https://www.instagram.com/jonasbroms/
    about: Ask questions, get help and discuss new things you're building with me
  - name: ğŸ’¼ Jonas BrÃ¶ms LinkedIn
    url: https://www.linkedin.com/in/jonas-broms/
    about: Ask questions, get help and discuss new things you're building with me
